# Site settings
title: Your Title Here
baseurl: "/ods-jekyll-theme/"
author: Copyright &copy; 2021 - 2024 - Orange
lang: en_US

# Build settings
safe: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  indentWidth: 4
  precision: 10
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
